ERROR 2024-12-18 15:17:54,236 log Internal Server Error: /aplicatie1/cumpara_cos/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 698, in cumpara_cos
    for item in cos_virtual.split(","):
                ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
ERROR 2024-12-18 15:17:54,238 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 500 76887
ERROR 2024-12-18 15:19:41,197 log Internal Server Error: /aplicatie1/cumpara_cos/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 699, in cumpara_cos
    for item in cos_virtual.split(","):
                ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
ERROR 2024-12-18 15:19:41,199 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 500 76874
ERROR 2024-12-18 15:23:02,554 log Internal Server Error: /aplicatie1/cumpara_cos/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 720, in cumpara_cos
    email.send()
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\mail\backends\smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 841, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
ERROR 2024-12-18 15:23:02,569 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 500 114828
ERROR 2025-01-07 11:35:25,780 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:35:25,787 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/profile/ HTTP/1.1" 500 220428
ERROR 2025-01-07 11:37:25,136 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:37:25,140 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/profile/ HTTP/1.1" 500 220561
ERROR 2025-01-07 11:37:29,706 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:37:29,710 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 219862
ERROR 2025-01-07 11:39:15,105 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:39:15,110 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 243966
ERROR 2025-01-07 11:39:26,214 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:39:26,220 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 243978
ERROR 2025-01-07 11:40:50,020 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:40:50,025 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 244462
ERROR 2025-01-07 12:38:50,094 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 494, in user_login
    return render(request, 'login.html', context)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'filtrare_filme_2' not found. 'filtrare_filme_2' is not a valid view function or pattern name.
ERROR 2025-01-07 12:38:50,098 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 147252
ERROR 2025-01-07 12:39:31,792 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 494, in user_login
    return render(request, 'login.html', context)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contact' not found. 'contact' is not a valid view function or pattern name.
ERROR 2025-01-07 12:39:31,795 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 147077
ERROR 2025-01-07 12:54:21,592 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 474, in user_login
    if (current_time - time) < datetime.timedelta(minutes=2)
                               ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
ERROR 2025-01-07 12:54:21,595 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 500 72323
ERROR 2025-01-07 12:56:42,262 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 474, in user_login
    if (current_time - time) < datetime.timedelta(minutes=2)
                               ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
ERROR 2025-01-07 12:56:42,264 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 500 72323
ERROR 2025-01-07 13:50:55,263 log Internal Server Error: /aplicatie1/profile/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 515, in profile
    return render(request, 'profile.html', context)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'promotii' not found. 'promotii' is not a valid view function or pattern name.
ERROR 2025-01-07 13:50:55,267 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 500 173376
